import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Dancing_Script} from "next/font/google"
// import Navbar from '@/components/COMPONENTS/Navbar'

const inter = Inter({ subsets: ['latin'] })
// const great_Vibes =Great_Vibes({ weight:  ["400"] })
const Dancing = Dancing_Script({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})
export const metadata: Metadata = {
  title: 'MultiPages Website',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
       {/* <Navbar /> */}
      <body className={inter.className}>{children}
        
      
  
    </body>
      
    </html>
  )
}
